from __future__ import annotations

from typing import FrozenSet

MODE_DEFAULT = "default"
MODE_CUSTOM = "custom"
MODES: FrozenSet[str] = frozenset({MODE_DEFAULT, MODE_CUSTOM})

PROVIDER_SERPER = "serper"
PROVIDER_TAVILY = "tavily"
PROVIDER_BRAVE = "brave"
PROVIDER_SERPAPI = "serpapi"
PROVIDER_EXA = "exa"
PROVIDER_PERPLEXITY = "perplexity"
PROVIDERS: FrozenSet[str] = frozenset(
    {
        PROVIDER_SERPER,
        PROVIDER_TAVILY,
        PROVIDER_BRAVE,
        PROVIDER_SERPAPI,
        PROVIDER_EXA,
        PROVIDER_PERPLEXITY,
    }
)

STATUS_UNSET = "unset"
STATUS_UNTESTED = "untested"
STATUS_VALID = "valid"
STATUS_INVALID = "invalid"
STATUS_QUOTA_EXHAUSTED = "quota_exhausted"
STATUS_RATE_LIMITED = "rate_limited"
STATUS_PROVIDER_ERROR = "provider_error"
STATUSES: FrozenSet[str] = frozenset(
    {
        STATUS_UNSET,
        STATUS_UNTESTED,
        STATUS_VALID,
        STATUS_INVALID,
        STATUS_QUOTA_EXHAUSTED,
        STATUS_RATE_LIMITED,
        STATUS_PROVIDER_ERROR,
    }
)

ERROR_NOT_CONFIGURED = "not_configured"
ERROR_INVALID_KEY = "invalid_key"
ERROR_QUOTA_EXHAUSTED = "quota_exhausted"
ERROR_RATE_LIMITED = "rate_limited"
ERROR_TIMEOUT = "timeout"
ERROR_PROVIDER_ERROR = "provider_error"
ERROR_EMPTY_RESULT = "empty_result"
ERROR_MASTER_KEY_REQUIRED = "master_key_required"

PUBLIC_ERROR_NOT_CONFIGURED = "CUSTOM_PROVIDER_NOT_CONFIGURED"
PUBLIC_ERROR_KEY_INVALID = "CUSTOM_PROVIDER_KEY_INVALID"
PUBLIC_ERROR_QUOTA_EXHAUSTED = "CUSTOM_PROVIDER_QUOTA_EXHAUSTED"
PUBLIC_ERROR_RATE_LIMITED = "CUSTOM_PROVIDER_RATE_LIMITED"
PUBLIC_ERROR_TIMEOUT = "CUSTOM_PROVIDER_TIMEOUT"
PUBLIC_ERROR_PROVIDER_ERROR = "CUSTOM_PROVIDER_ERROR"
PUBLIC_ERROR_EMPTY_RESULT = "CUSTOM_PROVIDER_EMPTY_RESULT"
