STEEL_DELAY_MS = 2000.0
STEEL_MAX_RETRIES = 0
STEEL_CONCURRENCY = 3

WEB_FETCH_MIN_CONTENT_LENGTH = 400
WEB_FETCH_LAST_RESORT_MIN_LENGTH = 50
WEB_FETCH_MAX_DOCUMENT_SIZE = 50 * 1024 * 1024
WEB_FETCH_STATIC_TIMEOUT = 15.0
WEB_FETCH_BROWSER_TIMEOUT = 30.0
WEB_FETCH_LOCAL_WORKER_COUNT = 5
WEB_FETCH_LOCAL_WORKER_CONCURRENCY = 2
WEB_FETCH_LOCAL_WORKER_TIMEOUT = 30.0
WEB_FETCH_LOCAL_WORKER_RESTART_AFTER = 200
WEB_FETCH_CACHE_TTL_SECONDS = 10 * 60
WEB_FETCH_CACHE_MAX_ITEMS = 128
