OCR_BACKEND = "paddleocr"
OCR_LANGUAGE = "ch"
OCR_TIMEOUT_SECONDS = 120.0
OCR_WORKER_MODE = "lazy_persistent"
OCR_WORKER_IDLE_TTL_SECONDS = 30 * 60

OCR_USE_DOC_ORIENTATION_CLASSIFY = False
OCR_USE_DOC_UNWARPING = False
OCR_USE_TEXTLINE_ORIENTATION = False
