PAPER_SEARCH_MAX_RESULTS = 8
PAPER_SEARCH_TIMEOUT_SECONDS = 12.0
PAPER_SEARCH_CACHE_TTL_SECONDS = 3600.0
PAPER_SEARCH_TOOL_RESULT_MAX_CHARS = 12000

EXA_FAST_NUM_RESULTS_PER_REWRITE = 20
EXA_DEEP_NUM_RESULTS_PER_REWRITE = 30

QUERY_VARIANTS_LIMIT_FAST = 2
QUERY_VARIANTS_LIMIT_DEEP = 4

ARXIV_API_MIN_INTERVAL_SECONDS = 3.0
ARXIV_HYDRATION_CACHE_TTL_SECONDS = 86400.0
ARXIV_MONITOR_TIMEOUT_SECONDS = 10.0

DOI_HYDRATION_MAX_CONCURRENCY = 5
DOI_HYDRATION_TIMEOUT_SECONDS = 3.0
DOI_HYDRATION_LIMIT_FAST = 8
DOI_HYDRATION_LIMIT_DEEP = 20
DOI_HYDRATION_POSITIVE_TTL_SECONDS = 7 * 24 * 3600.0
DOI_HYDRATION_NEGATIVE_TTL_SECONDS = 24 * 3600.0

FIND_SIMILAR_SEED_COUNT = 3
FIND_SIMILAR_RESULTS_PER_SEED = 5
FIND_SIMILAR_MIN_METADATA_CONFIDENCE = 0.48

RRF_K = 60
MAX_ADJUSTMENT_RATIO = 0.25
