PDF_MAX_PAGES = 80

PDF_MARKER_MIN_TEXT_CHARS = 30

PDF_PAGE_MIN_TEXT_CHARS = 30
PDF_SCANNED_IMAGE_AREA_RATIO = 0.65
PDF_ENABLE_MIXED_PAGE_TYPE = True

PDF_RENDER_DPI = 220
PDF_MAX_IMAGE_PIXELS = 36_000_000
PDF_RENDER_ALPHA = False

PDF_SCANNED_OCR_ENABLED = True
PDF_SCANNED_OCR_MAX_PAGES = PDF_MAX_PAGES
PDF_SCANNED_OCR_CONCURRENCY = 2
