PAPER_SEARCH_TIMEOUT_SECONDS = 12.0
PAPER_SEARCH_MAX_RESULTS = 8
PAPER_SEARCH_CACHE_TTL_SECONDS = 3600.0
PAPER_SEARCH_TOOL_RESULT_MAX_CHARS = 12000

SOURCE_RATE_LIMIT_SECONDS = 1.0
ARXIV_MIN_INTERVAL_SECONDS = 3.0
ARXIV_MAX_RESULTS = 5
ARXIV_CLIENT_REQUEST_TIMEOUT_SECONDS = 8.0
UNPAYWALL_ENRICH_LIMIT = 5
