from enum import StrEnum


class SageMathTask(StrEnum):
    MODULAR_ARITHMETIC = "modular_arithmetic"
    MODULAR_INVERSE = "modular_inverse"
    GCD = "gcd"
    LCM = "lcm"
    XGCD = "xgcd"
    PRIME_FACTORIZATION = "prime_factorization"
    IS_PRIME = "is_prime"
    NEXT_PRIME = "next_prime"
    EULER_PHI = "euler_phi"
    DIVISORS = "divisors"
    SIGMA = "sigma"
    MOEBIUS = "moebius"
    CRT = "crt"
    FINITE_FIELD_BASIC = "finite_field_basic"
    FINITE_FIELD_OPERATION = "finite_field_operation"
    POLYNOMIAL_FACTOR_OVER_FIELD = "polynomial_factor_over_field"
    POLYNOMIAL_ROOTS_OVER_FIELD = "polynomial_roots_over_field"
    POLYNOMIAL_GCD_OVER_FIELD = "polynomial_gcd_over_field"
    POLYNOMIAL_IS_IRREDUCIBLE_OVER_FIELD = "polynomial_is_irreducible_over_field"
    POLYNOMIAL_RESULTANT = "polynomial_resultant"
    POLYNOMIAL_DISCRIMINANT = "polynomial_discriminant"
    POLYNOMIAL_SQUAREFREE_DECOMPOSITION = "polynomial_squarefree_decomposition"
    POLYNOMIAL_QUOTIENT_REMAINDER = "polynomial_quotient_remainder"
    MATRIX_SMITH_FORM = "matrix_smith_form"
    MATRIX_HERMITE_FORM = "matrix_hermite_form"
    MATRIX_MINIMAL_POLYNOMIAL = "matrix_minimal_polynomial"
    MATRIX_CHARACTERISTIC_POLYNOMIAL = "matrix_characteristic_polynomial"
    MATRIX_KERNEL = "matrix_kernel"
    MATRIX_IMAGE = "matrix_image"


