PDF_PAGE_MIN_TEXT_CHARS = 30
PDF_SCANNED_IMAGE_AREA_RATIO = 0.65
PDF_ENABLE_MIXED_PAGE_TYPE = True
PDF_MAX_PAGES = 80

# Legacy compatibility knob. New code uses the more granular concurrency
# settings below so PyMuPDF, Camelot, OCR, and PP-Structure do not amplify each
# other's CPU usage.
PDF_TABLE_CONCURRENCY = 4

PDF_RENDER_DPI = 220
PDF_RENDER_DPI_HIGH_QUALITY = 300
PDF_MAX_IMAGE_PIXELS = 36_000_000
PDF_RENDER_ALPHA = False

PDF_TABLE_MODE = "auto"  # off / auto / full
PDF_EXTRACT_TABLES = True
PDF_TABLE_USE_PYMUPDF_FIND_TABLES = True
PDF_TABLE_USE_CAMELOT = True
PDF_PYMUPDF_TABLE_CONCURRENCY = 2

PDF_CAMELOT_ENABLE_LATTICE = True
PDF_CAMELOT_ENABLE_STREAM = True
PDF_CAMELOT_STREAM_REQUIRE_GATE = True
PDF_CAMELOT_CONCURRENCY = 1
PDF_CAMELOT_BATCH_SIZE = 8
PDF_CAMELOT_RUN_BOTH_FLAVORS = False
PDF_CAMELOT_LATTICE_PROCESS_BACKGROUND = False
PDF_CAMELOT_STRIP_TEXT = "\n"
PDF_CAMELOT_SUPPRESS_NO_TABLE_WARNINGS = True
PDF_CAMELOT_MAX_TABLES_PER_PAGE = 20

PDF_CAMELOT_MIN_ROWS = 2
PDF_CAMELOT_MIN_COLS = 2
PDF_CAMELOT_MIN_ACCURACY = 80.0
PDF_CAMELOT_MAX_WHITESPACE = 70.0

PDF_PYMUPDF_TABLE_MIN_ROWS = 2
PDF_PYMUPDF_TABLE_MIN_COLS = 2
PDF_PYMUPDF_TABLE_MIN_NON_EMPTY_RATIO = 0.3

PDF_SCANNED_OCR_ENABLED = True
PDF_SCANNED_OCR_MAX_PAGES = PDF_MAX_PAGES
PDF_SCANNED_OCR_CONCURRENCY = 2
PDF_SCANNED_TABLES_ENABLED = True
PDF_SCANNED_TABLES_MAX_PAGES = 30
PDF_SCANNED_TABLE_CONCURRENCY = 1
PDF_SCANNED_TABLE_REQUIRE_GATE = True
